import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const contractsRoot = resolve(scriptDir, "..");
const repoRoot = resolve(contractsRoot, "..", "..");
const abiOutputDir = resolve(repoRoot, "packages", "shared", "src", "abi");

const artifacts = [
  {
    artifactPath: resolve(
      contractsRoot,
      "out",
      "AwardDistributionRegistry.sol",
      "AwardDistributionRegistry.json"
    ),
    outputPath: resolve(abiOutputDir, "awardDistributionRegistry.ts"),
    exportName: "awardDistributionRegistryAbi"
  },
  {
    artifactPath: resolve(contractsRoot, "out", "MockUSDC.sol", "MockUSDC.json"),
    outputPath: resolve(abiOutputDir, "mockUsdc.ts"),
    exportName: "mockUsdcAbi"
  }
];

await mkdir(abiOutputDir, { recursive: true });

for (const artifact of artifacts) {
  const artifactJson = JSON.parse(await readFile(artifact.artifactPath, "utf8"));

  if (!Array.isArray(artifactJson.abi)) {
    throw new Error(`Artifact does not include an ABI array: ${artifact.artifactPath}`);
  }

  const source = [
    "/* Auto-generated by packages/contracts/scripts/copyAbi.mjs. */",
    `export const ${artifact.exportName} = ${JSON.stringify(artifactJson.abi, null, 2)} as const;`,
    ""
  ].join("\n");

  await writeFile(artifact.outputPath, source, "utf8");
}

await writeFile(
  resolve(abiOutputDir, "index.ts"),
  [
    "/* Auto-generated by packages/contracts/scripts/copyAbi.mjs. */",
    'export * from "./awardDistributionRegistry.js";',
    'export * from "./mockUsdc.js";',
    ""
  ].join("\n"),
  "utf8"
);

console.log(`Copied ${artifacts.length} contract ABIs to ${abiOutputDir}`);
