import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const contractsRoot = resolve(scriptDir, "..");
const repoRoot = resolve(contractsRoot, "..", "..");

const args = parseArgs(process.argv.slice(2));
const chainId = args.chainId ?? process.env.CHAIN_ID ?? "31337";
const rpcUrl = args.rpcUrl ?? process.env.RPC_URL ?? "http://127.0.0.1:8545";
const blockExplorerUrl = args.blockExplorerUrl ?? process.env.BLOCK_EXPLORER_URL ?? "";

const deployment = resolveDeployment({
  chainId,
  registryAddress: args.registry ?? process.env.REGISTRY_CONTRACT_ADDRESS,
  mockUsdcAddress:
    args.mockUsdc ?? args.mockUsdcAddress ?? process.env.MOCK_USDC_ADDRESS,
  broadcastFile: args.broadcast ?? process.env.DEPLOYMENT_BROADCAST_FILE
});

writeRootEnv({
  chainId,
  rpcUrl,
  blockExplorerUrl,
  registryAddress: deployment.registryAddress,
  mockUsdcAddress: deployment.mockUsdcAddress
});
writeWebEnv({
  chainId,
  rpcUrl,
  blockExplorerUrl,
  registryAddress: deployment.registryAddress,
  mockUsdcAddress: deployment.mockUsdcAddress
});

console.log(
  [
    "Synced contract deployment env",
    `chainId=${chainId}`,
    `registry=${deployment.registryAddress}`,
    `mockUsdc=${deployment.mockUsdcAddress}`
  ].join("\n")
);

function parseArgs(values) {
  const parsed = {};

  for (let index = 0; index < values.length; index += 1) {
    const value = values[index];

    if (value === "--") {
      continue;
    }

    if (!value.startsWith("--")) {
      continue;
    }

    const [rawKey, inlineValue] = value.slice(2).split("=", 2);
    const key = rawKey.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
    parsed[key] = inlineValue ?? values[index + 1];

    if (inlineValue === undefined) {
      index += 1;
    }
  }

  return parsed;
}

function resolveDeployment({ chainId, registryAddress, mockUsdcAddress, broadcastFile }) {
  if (registryAddress && mockUsdcAddress) {
    return {
      registryAddress: requireAddress(registryAddress, "REGISTRY_CONTRACT_ADDRESS"),
      mockUsdcAddress: requireAddress(mockUsdcAddress, "MOCK_USDC_ADDRESS")
    };
  }

  const artifact = readBroadcastArtifact(
    broadcastFile ?? resolve(contractsRoot, "broadcast", "Deploy.s.sol", chainId, "run-latest.json")
  );

  return {
    registryAddress: requireAddress(
      registryAddress ?? findContractAddress(artifact, "AwardDistributionRegistry"),
      "REGISTRY_CONTRACT_ADDRESS"
    ),
    mockUsdcAddress: requireAddress(
      mockUsdcAddress ?? findContractAddress(artifact, "MockUSDC"),
      "MOCK_USDC_ADDRESS"
    )
  };
}

function readBroadcastArtifact(path) {
  if (!existsSync(path)) {
    throw new Error(
      [
        `Deployment broadcast file was not found: ${path}`,
        "Pass addresses directly:",
        "corepack pnpm contracts:sync-env -- --registry 0x... --mock-usdc 0x...",
        "or pass --broadcast path/to/run-latest.json."
      ].join("\n")
    );
  }

  return JSON.parse(readFileSync(path, "utf8"));
}

function findContractAddress(artifact, contractName) {
  const transaction = artifact.transactions?.find(
    (item) => item.contractName === contractName && item.contractAddress
  );

  if (!transaction?.contractAddress) {
    throw new Error(`Could not find ${contractName} address in deployment broadcast.`);
  }

  return transaction.contractAddress;
}

function requireAddress(value, name) {
  if (!/^0x[a-fA-F0-9]{40}$/.test(value ?? "")) {
    throw new Error(`${name} must be an EVM address. Received: ${value ?? ""}`);
  }

  return value;
}

function writeRootEnv(values) {
  const content = [
    "# Generated by corepack pnpm contracts:sync-env",
    "NODE_ENV=development",
    "",
    "API_PORT=4000",
    "DATABASE_URL=file:./data/awardblock.sqlite",
    "SESSION_COOKIE_NAME=awardblock_session",
    "SESSION_SECRET=local-demo-session-secret",
    "INVITE_TOKEN_SECRET=local-demo-invite-secret",
    "CORS_ORIGIN=http://localhost:5173",
    "",
    "VITE_API_BASE_URL=http://localhost:4000",
    `VITE_CHAIN_ID=${values.chainId}`,
    `VITE_RPC_URL=${values.rpcUrl}`,
    `VITE_BLOCK_EXPLORER_URL=${values.blockExplorerUrl}`,
    `VITE_REGISTRY_CONTRACT_ADDRESS=${values.registryAddress}`,
    `VITE_MOCK_USDC_ADDRESS=${values.mockUsdcAddress}`,
    "",
    `CHAIN_ID=${values.chainId}`,
    `RPC_URL=${values.rpcUrl}`,
    `REGISTRY_CONTRACT_ADDRESS=${values.registryAddress}`,
    `MOCK_USDC_ADDRESS=${values.mockUsdcAddress}`,
    ""
  ].join("\n");

  writeFileSync(resolve(repoRoot, ".env.local"), content, "utf8");
}

function writeWebEnv(values) {
  const webRoot = resolve(repoRoot, "apps", "web");
  mkdirSync(webRoot, { recursive: true });
  const content = [
    "# Generated by corepack pnpm contracts:sync-env",
    "VITE_API_BASE_URL=http://localhost:4000",
    `VITE_CHAIN_ID=${values.chainId}`,
    `VITE_RPC_URL=${values.rpcUrl}`,
    `VITE_BLOCK_EXPLORER_URL=${values.blockExplorerUrl}`,
    `VITE_REGISTRY_CONTRACT_ADDRESS=${values.registryAddress}`,
    `VITE_MOCK_USDC_ADDRESS=${values.mockUsdcAddress}`,
    ""
  ].join("\n");

  writeFileSync(resolve(webRoot, ".env.local"), content, "utf8");
}
